version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://resetbiology:password123@db:5432/resetbiology
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=development-secret-change-in-production
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=resetbiology
      - POSTGRES_USER=resetbiology
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123

volumes:
  postgres_data: